### ISSUE TITLE
Are you really meant to be a public repository?

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/q-go-assessment#4]
We have noticed this repository is marked as public.  There are certain standards required before a repository in the `sky-uk` org can be made public, including the presence of valid `LICENSE.md`, `README.md`, and `CONTRIBUTING.md` files.
Unless there is good reason to make a repository public, we create as private by default, since we only want to publicly expose repositories that are of a high standard, in order to project a positive profile to the wider development community.
-  Repos without license information are immediately made private.
-  Repos failing the other criteria will be made private after 30 days.

Please resolve these problems ASAP and close this GitHub issue when you have done so.

If you have any questions, please ask them on the [#github](https://sky.slack.com/archives/github) Slack channel.

**Comment by karl** [comment]
This is a public repo so that candidates are able to download the code to work on at home.

It already has a README and LICENSE file. It doesn't accept contributions so we haven't added a `CONTRIBUTING.md` file but we can add a blank one if that is needed to pass the checklist.

**Comment by oliverlockwood** [comment]
@karl Thanks for commenting on this.

I have to say that I don’t see any reason why a tech test should be public (you can still grant access to individual candidates, of course), and many reasons why it *shouldn’t* be public (anyone can see how we test people, regardless of whether they’re a current candidate or not, allowing people to game the assessment, etc).  I don't think it really improves Sky's portrayal to the development community at large.

Do you have any other justification?

**Comment by karl** [comment]
We want candidate to be able to download the latest version of the assessment in a self service manner as it reduces the maintenance burden on our side. 

For example we don't want to spend time managing individual access to a repo, or notifying recruiters whenever we tweak the assessment.

Making this repo public was the quickest way to get this working. We have hooked it up to a simple GitHub pages site here: https://sky-uk.github.io/q-go-assessment/

We don't have any worries about letting people view the assessment even when they are not a candidate. Experience has told us that candidates tend not to game the assessment, and even if they did they would be filtered out at a later stage of hiring (this isn't the only technical assessment we do).

If there is a strong desire to make this private then I'd ask that you work with us to come up with an approach that allows us to still provide self service downloads to candidates.
